apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "dracon"
  labels:
    app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: {{ .Release.Name }}
spec:
  mode: Single
  externalAccess:
    type: None
  auth:
    jwtSecretName: None # Disable auth
  image: docker.io/arangodb/arangodb:3.7.10
