---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -golang-project
components:
  - pkg:helm/dracon-oss-components/base
  - pkg:helm/dracon-oss-components/git-clone
  - pkg:helm/dracon-oss-components/producer-golang-gosec
  - pkg:helm/dracon-oss-components/producer-aggregator
  - pkg:helm/dracon-oss-components/enricher-codeowners
  - pkg:helm/dracon-oss-components/enricher-aggregator
  - pkg:helm/dracon-oss-components/consumer-stdout-json
#  - pkg:helm/dracon-oss-components/producer-golang-nancy
#  - pkg:helm/dracon-oss-components/producer-aggregator
#  - pkg:helm/dracon-oss-components/enricher-codeowners
#  - pkg:helm/dracon-oss-components/enricher-aggregator
#  - pkg:helm/dracon-oss-components/consumer-mongodb
#  - pkg:helm/dracon-oss-components/consumer-elasticsearch
