---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dracon-golang-project-
spec:
  pipelineRef:
    name: dracon-golang-project
  params:
  - name: git-clone-url
    value: https://github.com/ocurity/e2e-monorepo.git
  - name: git-clone-subdirectory
    value: source-code
  workspaces:
  - name: output
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
