# subinclude("//build/defs:dracon")

# dracon_pipeline(
#     name = "jira-project",
#     components = [
#         "//components/base:k8s",
#         "//components/consumers/jira:k8s",
#         "//components/enrichers/aggregator:k8s",
#         "//components/enrichers/deduplication:k8s",
#         "//components/producers/aggregator:k8s",
#         "//components/producers/trufflehog:k8s",
#         "//components/sources/git:k8s",
#     ],
#     kube_context = "//build/k8s/k3d:dracon",
#     kustomization_yaml = "kustomization.yaml",
#     pipelinerun = "//examples/pipelines/jira-project/pipelinerun:pipelinerun",
# )
