---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-java-findsecbugs
  labels:
    v1.dracon.ocurity.com/component: producer
    v1.dracon.ocurity.com/test-type: sast
spec:
  params:
  - name: producer-java-findsecbugs-extra-flags
    type: array
    default: []
  - name: producer-java-findsecbugs-jar-url
    type: string
  volumes:
  - name: scratch
    emptyDir: {}
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: get-jar
    image: busybox:latest
    script: |
      wget "$(params.producer-java-findsecbugs-jar-url)" -O "$(workspaces.output.path)/main.jar"
  - name: run-findsecbugs
    imagePullPolicy: IfNotPresent
    image: docker.io/captainfoobar/findsecbugs:1.12.0.3
    command: [/findsecbugs/run-findsecbugs-exit-zero.sh]
    args:
      - -quiet
      - -xml
      - -progress
      - -output
      - /scratch/out.xml
      - "$(params.producer-java-findsecbugs-extra-flags[*])"
      - "$(workspaces.output.path)/main.jar"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
  - name: debug
    imagePullPolicy: IfNotPresent
    image: busybox:latest
    script: |
      ls -lah /scratch
    volumeMounts:
    - mountPath: /scratch
      name: scratch

  - name: produce-issues
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.container_registry }}/components/producers/java-findsecbugs:latest'
    command: ["/app/components/producers/java-findsecbugs/java-findsecbugs-parser"]
    args:
    - "-in=/scratch/out.xml"
    - "-out=$(workspaces.output.path)/.dracon/producers/java-findsecbugs.pb"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
