---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-checkov
  labels:
    v1.dracon.ocurity.com/component: producer
    v1.dracon.ocurity.com/test-type: sast
    v1.dracon.ocurity.com/language: iac
spec:
  description: Analyse IAC source code to look for security issues.
  params:
  - name: producer-checkov-cyclonedx-target-override
    type: string
    default: ""
  volumes:
    - name: scratch
      emptyDir: {}
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-checkov
    image: bridgecrew/checkov:3.2.255
    command: [/usr/local/bin/checkov]
    args:
    - --skip-download
    - --directory
    - "$(workspaces.output.path)/source-code"
    - --output=cyclonedx_json
    - --output=sarif
    - --output-file-path
    - /scratch    
    - --soft-fail
    volumeMounts:
    - mountPath: /scratch
      name: scratch  
  - name: produce-issues
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.image.registry }}/components/producers/checkov:{{ .Chart.AppVersion }}'
    command: ["/app/components/producers/checkov/checkov-parser"]
    args:
    - "-in=/scratch/results_sarif.sarif"
    - "-out=$(workspaces.output.path)/.dracon/producers/checkov-sarif.pb"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
