---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-dependency-track
  labels:
    v1.dracon.ocurity.com/component: producer
spec:
  description: Generate a Dependency-Track report from source code.
  params:
  - name: producer-dependency-track-project-id
    type: string
    default: ""
  - name: producer-dependency-track-fetch-vulnerabilities
    type: string
    default: ""
  - name: producer-dependency-track-url
    type: string
    default: ""
  - name: producer-dependency-track-api-key
    type: string
    default: ""
  volumes:
    - name: scratch
      emptyDir: {}
  workspaces:
    - name: source-code-ws
      description: The workspace containing the dependency track results.
  steps:
  - name: produce-issues
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.image.registry }}/components/producers/dependency-track:{{ .Chart.AppVersion }}'
    command: ["app/components/producers/dependency-track/dependency-track-parser"]
    args:
    - "-fetchVulnerabilities=$(params.producer-dependency-track-fetch-vulnerabilities)"
    - "-projectID=$(params.producer-dependency-track-project-id)"
    - "-apiKey=$(params.producer-dependency-track-api-key)"
    - "-url=$(params.producer-dependency-track-url)"
    - "-in=/scratch/out.json"
    - "-out=$(workspaces.source-code-ws.path)/.dracon/producers/dependency-track.pb"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
