---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dracon-typescript-project-
  namespace: dracon
spec:
  pipelineRef:
    name: dracon-typescript-project
  params:
  - name: git-clone-url
    # TODO(OCU-154): Switch to ocurity/e2e-monorepo
    value: https://github.com/appsecco/dvna.git
  workspaces:
  - name: output
    subPath: source-code
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
