# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: 'dracon'

  # A short description of the repository that will show up on GitHub
  description: 'Security scanning & static analysis tool - forked and rewritten from @thought-machine/dracon'

  # A URL with more information about the repository
  homepage: 'https://ocurity.com'

  # A comma-separated list of topics to set on the repository
  topics: 'SAST, DAST, DevSecOps, Pipelines, Tekton'

  # Either `true` to make the repository private, or `false` to make it public.
  private: public

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: true

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false # paid feature

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: false

  # Updates the default branch for this repository.
  default_branch: 'main'

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: false

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

  # Either `true` to enable automatic deletion of branches on merge, or `false` to disable
  delete_branch_on_merge: true

  # Either `true` to enable automated security fixes, or `false` to disable
  # automated security fixes.
  enable_automated_security_fixes: true

  # Either `true` to enable vulnerability alerts, or `false` to disable
  # vulnerability alerts.
  enable_vulnerability_alerts: true

# Labels: define labels for Issues and Pull Requests
# These are based off: https://github.com/seantrane/github-label-presets
labels:
  # t-shirt sizing of effort
  - name: 'effort: 1d'
    color: '91ca55'
    description: 'XS (~1d) amount of effort to complete'

  - name: 'effort: 3d'
    color: 'c2e2a2'
    description: 'S (~3d) amount of effort to complete'

  - name: 'effort: 5d'
    color: 'e9f4dc'
    description: 'M (~5d) amount of effort to complete'

  - name: 'effort: 8d'
    color: 'fef2c0'
    description: 'L (~8d) amount of effort to complete'

  - name: 'effort: 13d+'
    color: 'fbca04'
    description: 'XL (~13d+) amount of effort to complete'

  # issue priority
  - name: 'priority: critical'
    color: 'd73a4a'
    description: 'Something that should be done ASAP.'

  - name: 'priority: need'
    color: 'f6b26b'
    description: 'Something that needs to be done.'

  - name: 'priority: want'
    color: '6fa8dc'
    description: 'Something that should ideally be done.'

  - name: 'priority: nice to have'
    color: '93c47d'
    description: 'Something that is considered extra.'

  # types of issues or PRs
  - name: 'type: bug'
    color: 'd73a4a'
    description: "Something isn't working."

  - name: 'type: chore'
    color: 'fef2c0'
    description: "BAU maintenance."

  - name: 'type: docs'
    color: 'fef2c0'
    description: "Related to documentation."

  - name: 'type: feature'
    color: '5ebeff'
    description: Brand new functionality.

  - name: 'type: fix'
    color: '91ca55'
    description: "Iterations on existing features or infrastructure."

  - name: 'type: security'
    color: 'd73a4a'
    description: "Something is vulnerable or not secure."
