---
runner:
  go/staticcheck:
    cmd: |
      staticcheck $GO_PACKAGES
    errorformat:
      - '%E%f:%l:%c: %m'

  go/revive:
    cmd: |
      revive $GO_PACKAGES
    errorformat:
      - '%E%f:%l:%c: %m'

  go/vet:
    cmd: |
      go vet $GO_PACKAGES
    errorformat:
      - '%E%f:%l:%c: %m'

  go/gosec:
    cmd: |
      gosec -fmt golint $GO_PACKAGES
    errorformat:
      - '%E%f:%l:%c: %m'

  go/fmt:
    cmd: |
      gofumpt -d $GO_PACKAGES
    format: diff
    level: error

  buf/lint:
    cmd: buf lint --path api/
    level: error
    errorformat:
      - '%f:%l:%c:%m'

  buf/format:
    cmd: buf format --diff --path api/
    format: diff
    level: error
