---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: consumer-slack
  labels:
    v1.dracon.ocurity.com/component: consumer
spec:
  params:
    - name: consumer-slack-webhook
      type: string
    - name: consumer-slack-message-template
      type: string
      default: 'Dracon scan <scanID>, started at <scanStartTime>, completed with <numResults> findings, out of which, <newResults> new'
  workspaces:
    - name: source-code-ws
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-consumer
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.container_registry }}/components/consumers/slack/image:latest'
    command: ["/app/components/consumers/slack/slack"]
    args: [
      "-in", "$(workspaces.source-code-ws.path)/.dracon/enrichers/",
      "-webhook", "$(params.consumer-slack-webhook)",
      "-template", "$(params.consumer-slack-message-template)",
    ]
