---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -python-project
components:
  - pkg:helm/dracon-oss-components/base
  - pkg:helm/dracon-oss-components/git-clone
  - pkg:helm/dracon-oss-components/producer-aggregator
  - ./components/producers/python-bandit
  - ./components/producers/python-pip-safety
  - pkg:helm/dracon-oss-components/enricher-aggregator
  - ./components/enrichers/deduplication
  - ./components/consumers/mongodb
  - ./components/consumers/elasticsearch
