---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -python-project
namespace: dracon

resources:
  - ../../../components/base

components:
  - ../../../components/sources/git
  
  - ../../../components/producers/aggregator
  - ../../../components/producers/python-bandit
  - ../../../components/producers/python-pip-safety
  - ../../../components/enrichers/aggregator
  - ../../../components/enrichers/policy
  - ../../../components/enrichers/deduplication
  - ../../../components/consumers/mongodb
  - ../../../components/consumers/elasticsearch
