{{ if .Values.kibana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dracon.fullname" . }}-kb
  labels:
    {{- include "dracon.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "http"
spec:
  ingressClassName: {{ .Values.kibana.ingress.className }}
  defaultBackend:
    service:
      name: {{ include "dracon.fullname" . }}-kb-http
      port:
        name: http
  rules:
  - host: {{ .Values.kibana.ingress.host }}
  {{- if .Values.kibana.ingress.tlsEnabled }}
  tls:
  - hosts:
    - {{ .Values.kibana.ingress.host }}
    secretName: cert-kibana
  {{- end }}
{{ end }}