apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dracon.fullname" . }}-migrations
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dracon.fullname" . }}-migrations
subjects:
- kind: ServiceAccount
  name: {{ include "dracon.fullname" . }}-migrations
