---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: consumer-dependency-track
  labels:
    v1.dracon.ocurity.com/component: consumer
spec:
  description: Pushes findings to a Dependency-Track instance.
  params:
    - name: consumer-dependency-track-api-url
      type: string
    - name: consumer-dependency-track-project-name
      type: string
    - name: consumer-dependency-track-project-version
      type: string
    - name: consumer-dependency-track-token
      type: string
    - name: consumer-dependency-track-project-uuid
      type: string
    - name: consumer-dependency-track-owner-annotation
      type: string
      default: "Owner"
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-consumer
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.image.registry }}/components/consumers/dependency-track:{{ .Chart.AppVersion }}'
    command: ["/app/components/consumers/dependency-track/dependency-track"]
    args: [
      "-in", "$(workspaces.output.path)/.dracon/enrichers/",
      "-url", "$(params.consumer-dependency-track-api-url)",
      "-apiKey", "$(params.consumer-dependency-track-token)",
      "-projectName", "$(params.consumer-dependency-track-project-name)",
      "-projectVersion", "$(params.consumer-dependency-track-project-version)",
      "-projectUUID", "$(params.consumer-dependency-track-project-uuid)",
      "-ownerAnnotation","$(params.consumer-dependency-track-owner-annotation)"
    ]
