---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -misc-project
resources:
  - ../../../components/base/pipeline.yaml
components:
  - ../../../components/sources/git
  - ../../../components/producers/aggregator
  - ../../../components/producers/ossf-scorecard
  - ../../../components/producers/semgrep
  - ../../../components/enrichers/aggregator
  - ../../../components/enrichers/policy
  - ../../../components/enrichers/deduplication
  - ../../../components/consumers/mongodb
  - ../../../components/consumers/elasticsearch
