---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-docker-trivy
  labels:
    v1.dracon.ocurity.com/component: producer
    v1.dracon.ocurity.com/test-type: sca
spec:
  params:
  - name: producer-docker-trivy-flags
    type: array
    default: []
    description: Flags to pass to trivy. Optional.
  - name: producer-docker-trivy-target
    type: string
    default: "$(workspaces.output.path)"
    description: The target to scan.
  - name: producer-docker-trivy-format
    type: string
    default: json
    description: The format to output the results in. Valid values are `json`, `sarif`, `cyclonedx`. Default `json`.
  - name: producer-docker-trivy-command
    type: string
    default: image
    description: The command to run trivy with. Default `image`.
  volumes:
    - name: scratch
      emptyDir: {}
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-trivy
    image: docker.io/aquasec/trivy:0.54.1
    command: [trivy]
    args:
    - "$(params.producer-docker-trivy-flags[*])"
    - -f
    - $(params.producer-docker-trivy-format)
    - -o
    - /scratch/out.json
    - $(params.producer-docker-trivy-command)
    - $(params.producer-docker-trivy-target)
    volumeMounts:
    - mountPath: /scratch
      name: scratch

  - name: produce-issues
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.container_registry }}/components/producers/docker-trivy:{{ .Chart.AppVersion }}'
    command: ["/app/components/producers/docker-trivy/docker-trivy-parser"]
    args:
    - "-format=$(params.producer-docker-trivy-format)"
    - "-in=/scratch/out.json"
    - "-out=$(workspaces.output.path)/.dracon/producers/docker-trivy.pb"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
