---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-typescript-eslint
  labels:
    v1.dracon.ocurity.com/component: producer
spec:
  params:
    - name: producer-typescript-eslint-config-js
      type: string
      default: ""
  volumes:
  - name: scratch
    emptyDir: {}
  workspaces:
    - name: source-code-ws
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-eslint
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.container_registry }}/components/producers/typescript-eslint/eslint-wrapper/eslint:{{ default "latest" .Values.dracon_os_component_version }}'
    command: ["/home/node/workspace/eslint-wrapper"]
    args:
     - -t
     - $(workspaces.source-code-ws.path)
     - -c
     - "$(params.producer-typescript-eslint-config-js)"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
  - name: produce-issues
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.container_registry }}/components/producers/typescript-eslint/image:{{ default "latest" .Values.dracon_os_component_version }}'
    command: ["app/components/producers/typescript-eslint/typescript-eslint-parser"]
    args:
    - "-in=/scratch/out.json"
    - "-out=$(workspaces.source-code-ws.path)/.dracon/producers/typescript-eslint.pb"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
