---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: consumer-elasticsearch
  labels:
    v1.dracon.ocurity.com/component: consumer
spec:
  params:
    - name: consumer-elasticsearch-url
      type: string
      default: "http://dracon-es-http:9200"
    - name: consumer-elasticsearch-description-template
      type: string
      default: ""
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-consumer
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.container_registry }}/components/consumers/elasticsearch:latest'
    command: ["/app/components/consumers/elasticsearch/elasticsearch"]
    env:
    - name: ELASTICSEARCH_URL
      value: "$(params.consumer-elasticsearch-url)"
    args: [
      "-in", "$(workspaces.output.path)/.dracon/enrichers/",
      "-es-index", "dracon",
      "-descriptionTemplate","$(params.consumer-elasticsearch-description-template)"
    ]
