---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: consumer-elasticsearch
  labels:
    v1.dracon.ocurity.com/component: consumer
spec:
  params:
    - name: consumer-elasticsearch-url
      type: string
      default: "http://dracon-es-http.dracon.svc:9200"
  workspaces:
    - name: source-code-ws
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-consumer
    imagePullPolicy: IfNotPresent
    image: ghcr.io/ocurity/dracon/components/consumers/elasticsearch/image:latest
    command: ["/app/components/consumers/elasticsearch/elasticsearch"]
    env:
    - name: ELASTICSEARCH_URL
      value: "$(params.consumer-elasticsearch-url)"
    args: [
      "-in", "$(workspaces.source-code-ws.path)/.dracon/enrichers/",
      "-es-index", "dracon",
    ]
