apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ include "kibana.fullname" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
spec:
  version: 8.3.2
  image: docker.elastic.co/kibana/kibana:8.3.2
  count: 1
  elasticsearchRef:
    name: dracon
  # config:
  #   xpack.security.enabled: false
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    metadata:
      labels:
        team: "sys"
      annotations:
        app.gitlab.com/env: ci
        app.gitlab.com/app: sys-logging-elk
    spec:
      containers:
        - name: kibana
          resources:
            limits:
              memory: 4Gi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 5601
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
