---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kibana.fullname" . }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
  namespace: dracon
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "http"
spec:
  defaultBackend:
    service:
      name: dracon-kb-http
      port:
        name: http
  rules:
  - host: {{ .Values.ingress.host }}
  {{- if .Values.ingress.tlsEnabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: cert-kibana
  {{- end }}