---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -nancy-purl-project
resources:
  - ../../../components/base/pipeline.yaml
components:
  - ../../../components/sources/dependency
  - ../../../components/producers/aggregator
  - ../../../components/producers/golang-nancy
  - ../../../components/enrichers/aggregator
  - ../../../components/enrichers/deduplication
  - ../../../components/consumers/mongodb
