ARG BASE_MIGRATION_IMAGE
FROM ${BASE_MIGRATION_IMAGE:-scratch}

COPY ./bin/cmd/draconctl /bin/draconctl
COPY ./pkg/enrichment/migrations /etc/dracon/migrations/enrichment

ENTRYPOINT [ "/bin/draconctl" ]
