ARG BASE_MIGRATION_IMAGE

FROM ${BASE_MIGRATION_IMAGE:-scratch}

ARG GOOS=linux
ARG GOARCH=amd64

LABEL org.opencontainers.image.description "Draconctl is a command line tool for interacting with Dracon, you can find documentation for it at github.com/ocurity/dracon"

COPY ./bin/cmd/${GOOS}/${GOARCH}/draconctl /bin/draconctl
COPY ./pkg/enrichment/migrations /etc/dracon/migrations/enrichment

ENTRYPOINT [ "/bin/draconctl" ]
