apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "enrichment_db_migrations.fullname" . }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
