{{ if .Values.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "enrichment_db_migrations.fullname" . }}
  labels:
    {{- include "enrichment_db_migrations.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded, hook-failed
spec:
  template:
    metadata:
      name: enrichment-db-migrations
      labels:
        {{- include "enrichment_db_migrations.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: enrichment-db-migrations
        image: "{{ .Values.global.image.registry }}/draconctl:{{ .Values.image.tag | default .Chart.AppVersion }}"
        env:
          - name: DRACONCTL_MIGRATIONS_PATH
            value: "/etc/dracon/migrations/enrichment"
        command:
        - draconctl
        - migrations
        - apply
        - --url
        - "postgresql://{{ .Values.database.auth.username }}:{{ .Values.database.auth.password }}@{{ .Values.database.host }}/{{ .Values.database.auth.database }}?{{ .Values.database.auth.querystringargs}}"
      serviceAccountName: {{ include "enrichment_db_migrations.fullname" . }}
{{ end }}