---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dast-project
components:
  - pkg:helm/dracon-oss-components/base
  - pkg:helm/dracon-oss-components/producer-zaproxy
  - pkg:helm/dracon-oss-components/producer-aggregator
  - pkg:helm/dracon-oss-components/enricher-deduplication
  - pkg:helm/dracon-oss-components/enricher-aggregator
  - pkg:helm/dracon-oss-components/consumer-mongodb
  - pkg:helm/dracon-oss-components/consumer-elasticsearch
