---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dast-project
resources:
  - ../../../components/base/pipeline.yaml
components:
  - ../../../components/producers/aggregator
  # - ../../../components/producers/testsslsh
  - ../../../components/producers/zaproxy
  - ../../../components/enrichers/aggregator
  - ../../../components/enrichers/policy
  - ../../../components/enrichers/deduplication
  - ../../../components/consumers/mongodb
  - ../../../components/consumers/elasticsearch
