---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-semgrep
  labels:
    v1.dracon.ocurity.com/component: producer
spec:
  params:
  - name: producer-semgrep-rules-yaml
    type: string
    default: |
      rules: []
  - name: producer-semgrep-config-value
    type: string
    default: auto
  volumes:
    - name: scratch
      emptyDir: {}
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: write-semgrep-config
    image: docker.io/busybox:latest
    env:
      - name: SEMGREP_CONFIG
        value: $(params.producer-semgrep-rules-yaml)
    script: |
      printf '%s' "${SEMGREP_CONFIG}" > "/scratch/semgrep-rules.yaml"
      cat /scratch/semgrep-rules.yaml
    volumeMounts:
    - mountPath: /scratch
      name: scratch

  - name: run-semgrep
    image: docker.io/returntocorp/semgrep:1.11.0
    command: [/entrypoint.sh]
    args:
    - "semgrep"
    - "scan"
    - "--config"
    - "/scratch/semgrep-rules.yaml"
    - "--config=$(params.producer-semgrep-config-value)"
    - "--json"
    - "--output"
    - "/scratch/out.json"
    - "$(workspaces.output.path)"

    volumeMounts:
    - mountPath: /scratch
      name: scratch

  - name: produce-issues
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.container_registry }}/components/producers/semgrep:latest'
    command: ["/app/components/producers/semgrep/semgrep-parser"]
    args:
    - "-in=/scratch/out.json"
    - "-out=$(workspaces.output.path)/.dracon/producers/semgrep.pb"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
