---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dracon-github-project-
  namespace: dracon
spec:
  pipelineRef:
    name: dracon-github-project
  params:
  - name: repository_url
    value: "some repository to scan e.g. https://github.com/northdpole/go-dvwa"
  - name: repository_revision
    value: "a revision, branch, commit, etc, by default this will be the main/default branch on the latest commit e.g. 1d0c2df6b21c58783024249096fca67cd5f07bc3"
  - name: consumer-github-commit-sha
    value: "the commit the scan results affect, this is important for the github api, e.g. 1d0c2df6b21c58783024249096fca67cd5f07bc3"
  - name: consumer-github-ref
    value: " something like refs/pull/1/head, important to github, e.g. res/pull/1/head"
  - name: consumer-github-repo
    value: "name of the repo, e.g. go-dvwa"
  - name: consumer-github-token
    value: "a github pat with security_events scope"
  - name: consumer-github-user
    value: "a github username with access to upload results to the repo"
  workspaces:
  - name: source-code-ws
    subPath: source-code
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
