---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -iac-project
components:
  - pkg:helm/dracon-oss-components/base
  - pkg:helm/dracon-oss-components/git-clone
  - pkg:helm/dracon-oss-components/producer-docker-trivy
  - pkg:helm/dracon-oss-components/producer-kics
  - pkg:helm/dracon-oss-components/producer-terraform-tfsec
  - pkg:helm/dracon-oss-components/producer-aggregator
  - pkg:helm/dracon-oss-components/enricher-deduplication
  - pkg:helm/dracon-oss-components/enricher-aggregator
  - pkg:helm/dracon-oss-components/consumer-mongodb
  - pkg:helm/dracon-oss-components/consumer-elasticsearch