---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -iac-project
namespace: dracon

resources:
  - ../../../components/base

components:
  - ../../../components/sources/git
  
  - ../../../components/producers/aggregator
  - ../../../components/producers/docker-trivy
  - ../../../components/producers/kics
  - ../../../components/producers/terraform-tfsec
  - ../../../components/enrichers/aggregator
  - ../../../components/enrichers/policy
  - ../../../components/enrichers/deduplication
  - ../../../components/consumers/mongodb
  - ../../../components/consumers/elasticsearch
