apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dracon-migrations
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dracon-migrations
subjects:
- kind: ServiceAccount
  name: dracon-migrations
