---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: enricher-deduplication
  labels:
    v1.dracon.ocurity.com/component: enricher
spec:
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-enricher
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.container_registry }}/components/enrichers/deduplication:{{ .Chart.AppVersion }}'
    command: ["/app/components/enrichers/deduplication/deduplication"]
    env:
    - name: ENRICHER_READ_PATH
      value: $(workspaces.output.path)/.dracon/producers
    - name: ENRICHER_WRITE_PATH
      value: "$(workspaces.output.path)/.dracon/enrichers/deduplication"
    - name: ENRICHER_DB_CONNECTION
      value: postgresql://{{default "dracon" .Values.postgresql.auth.username }}:{{default "dracon" .Values.postgresql.auth.password }}@{{ default "dracon-enrichment-db" .Values.postgresql.host }}/{{default "dracon" .Values.postgresql.auth.database }}?{{default "sslmode=disable" .Values.postgresql.auth.querystringargs}}
