---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: consumer-defectdojo
  labels:
    v1.dracon.ocurity.com/component: consumer
spec:
  params:
    - name: consumer-defectdojo-api-url
      type: string
    - name: consumer-defectdojo-user
      type: string
    - name: consumer-defectdojo-token
      type: string
    - name: consumer-defectdojo-product-id
      type: string
    - name: consumer-defectdojo-description-template
      type: string
      default: ""
  workspaces:
    - name: source-code-ws
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-consumer
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.container_registry }}/components/consumers/defectdojo/image:{{ default "latest" .Values.dracon_os_component_version }}'
    command: ["/app/components/consumers/defectdojo/defectdojo"]
    args: [
      "-in", "$(workspaces.source-code-ws.path)/.dracon/enrichers/",
      "-dojoUser", "$(params.consumer-defectdojo-user)",
      "-dojoToken", "$(params.consumer-defectdojo-token)",
      "-dojoProductID", "$(params.consumer-defectdojo-product-id)",
      "-dojoURL", "$(params.consumer-defectdojo-api-url)",
      "-descriptionTemplate","$(params.consumer-defectdojo-description-template)",
    ]
