apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- release.yaml

# TODO: fix namespaces for tektoncd
#       some components are in the tekton-pipelines
#       and some other in tekton-pipeline-resolvers
# patches:
# - patch: |-
#     apiVersion: v1
#     kind: Namespace
#     metadata:
#       name: tekton-pipelines
#     $patch: delete
# - patch: |-
#     - op: remove
#       path: /metadata/namespace
#   target:
#     namespace: tekton-pipelines-resolvers
# - patch: |-
#     - op: replace
#       path: /spec/conversion/webhook/clientConfig/service/namespace
#       value: '{{ .Release.Namespace }}'
#   target:
#     version: v1
#     kind: CustomResourceDefinition
#     name: pipelineruns.tekton.dev
# - patch: |-
#     - op: replace
#       path: /spec/conversion/webhook/clientConfig/service/namespace
#       value: '{{ .Release.Namespace }}'
#   target:
#     version: v1
#     kind: CustomResourceDefinition
#     name: pipelines.tekton.dev
# - patch: |-
#     - op: replace
#       path: /spec/conversion/webhook/clientConfig/service/namespace
#       value: '{{ .Release.Namespace }}'
#   target:
#     version: v1
#     kind: CustomResourceDefinition
#     name: taskruns.tekton.dev
# - patch: |-
#     - op: replace
#       path: /spec/conversion/webhook/clientConfig/service/namespace
#       value: '{{ .Release.Namespace }}'
#   target:
#     version: v1
#     kind: CustomResourceDefinition
#     name: clustertasks.tekton.dev
# - patch: |-
#     - op: replace
#       path: /spec/conversion/webhook/clientConfig/service/namespace
#       value: '{{ .Release.Namespace }}'
#   target:
#     version: v1
#     kind: CustomResourceDefinition
#     name: resolutionrequests.resolution.tekton.dev
# - patch: |-
#     - op: replace
#       path: /spec/conversion/webhook/clientConfig/service/namespace
#       value: '{{ .Release.Namespace }}'
#   target:
#     version: v1
#     kind: CustomResourceDefinition
#     name: tasks.tekton.dev
# - patch: |-
#     - op: replace
#       path: /webhooks/0/clientConfig/service/namespace
#       value: '{{ .Release.Namespace }}'
#   target:
#     version: v1
#     kind: MutatingWebhookConfiguration
# - patch: |-
#     - op: replace
#       path: /webhooks/0/clientConfig/service/namespace
#       value: '{{ .Release.Namespace }}'
#   target:
#     version: v1
#     kind: ValidatingWebhookConfiguration
# - patch: |-
#     - op: replace
#       path: /subjects/0/namespace
#       value: '{{ .Release.Namespace }}'
#   target:
#     version: v1
#     kind: RoleBinding
# - patch: |-
#     - op: replace
#       path: /subjects/0/namespace
#       value: '{{ .Release.Namespace }}'
#   target:
#     version: v1
#     kind: ClusterRoleBinding

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ include "tekton.name" . }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "tekton.chart" . }}'
