---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -cdxgen-project
namespace: dracon

resources:
  - ../../../components/base

components:
  - ../../../components/sources/git
  
  - ../../../components/producers/aggregator
  - ../../../components/producers/cdxgen
  - ../../../components/enrichers/aggregator
  - ../../../components/enrichers/policy
  - ../../../components/consumers/stdout-json
