---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ include "tekton.name" . }}'
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "tekton.chart" . }}'
    pipeline.tekton.dev/release: v0.44.0
    version: v0.44.0
  name: verificationpolicies.tekton.dev
spec:
  group: tekton.dev
  names:
    categories:
      - tekton
      - tekton-pipelines
    kind: VerificationPolicy
    plural: verificationpolicies
    singular: verificationpolicy
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ include "tekton.name" . }}'
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "tekton.chart" . }}'
    pipeline.tekton.dev/release: v0.44.0
    version: v0.44.0
  name: clustertasks.tekton.dev
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: tekton-pipelines-webhook
          namespace: tekton-pipelines
      conversionReviewVersions:
        - v1beta1
  group: tekton.dev
  names:
    categories:
      - tekton
      - tekton-pipelines
    kind: ClusterTask
    plural: clustertasks
    singular: clustertask
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ include "tekton.name" . }}'
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "tekton.chart" . }}'
    pipeline.tekton.dev/release: v0.44.0
    version: v0.44.0
  name: customruns.tekton.dev
spec:
  group: tekton.dev
  names:
    categories:
      - tekton
      - tekton-pipelines
    kind: CustomRun
    plural: customruns
    singular: customrun
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=="Succeeded")].status
          name: Succeeded
          type: string
        - jsonPath: .status.conditions[?(@.type=="Succeeded")].reason
          name: Reason
          type: string
        - jsonPath: .status.startTime
          name: StartTime
          type: date
        - jsonPath: .status.completionTime
          name: CompletionTime
          type: date
      name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ include "tekton.name" . }}'
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "tekton.chart" . }}'
    pipeline.tekton.dev/release: v0.44.0
    version: v0.44.0
  name: pipelineresources.tekton.dev
spec:
  group: tekton.dev
  names:
    categories:
      - tekton
      - tekton-pipelines
    kind: PipelineResource
    plural: pipelineresources
    singular: pipelineresource
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ include "tekton.name" . }}'
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "tekton.chart" . }}'
    pipeline.tekton.dev/release: v0.44.0
    version: v0.44.0
  name: pipelineruns.tekton.dev
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: tekton-pipelines-webhook
          namespace: tekton-pipelines
      conversionReviewVersions:
        - v1beta1
        - v1
  group: tekton.dev
  names:
    categories:
      - tekton
      - tekton-pipelines
    kind: PipelineRun
    plural: pipelineruns
    shortNames:
      - pr
      - prs
    singular: pipelinerun
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=="Succeeded")].status
          name: Succeeded
          type: string
        - jsonPath: .status.conditions[?(@.type=="Succeeded")].reason
          name: Reason
          type: string
        - jsonPath: .status.startTime
          name: StartTime
          type: date
        - jsonPath: .status.completionTime
          name: CompletionTime
          type: date
      name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
    - additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=="Succeeded")].status
          name: Succeeded
          type: string
        - jsonPath: .status.conditions[?(@.type=="Succeeded")].reason
          name: Reason
          type: string
        - jsonPath: .status.startTime
          name: StartTime
          type: date
        - jsonPath: .status.completionTime
          name: CompletionTime
          type: date
      name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ include "tekton.name" . }}'
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "tekton.chart" . }}'
    pipeline.tekton.dev/release: v0.44.0
    version: v0.44.0
  name: pipelines.tekton.dev
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: tekton-pipelines-webhook
          namespace: tekton-pipelines
      conversionReviewVersions:
        - v1beta1
        - v1
  group: tekton.dev
  names:
    categories:
      - tekton
      - tekton-pipelines
    kind: Pipeline
    plural: pipelines
    singular: pipeline
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ include "tekton.name" . }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "tekton.chart" . }}'
    resolution.tekton.dev/release: devel
  name: resolutionrequests.resolution.tekton.dev
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: tekton-pipelines-webhook
          namespace: tekton-pipelines
      conversionReviewVersions:
        - v1alpha1
        - v1beta1
  group: resolution.tekton.dev
  names:
    categories:
      - tekton
      - tekton-pipelines
    kind: ResolutionRequest
    plural: resolutionrequests
    shortNames:
      - resolutionrequest
      - resolutionrequests
    singular: resolutionrequest
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=='Succeeded')].status
          name: Succeeded
          type: string
        - jsonPath: .status.conditions[?(@.type=='Succeeded')].reason
          name: Reason
          type: string
      deprecated: true
      name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
    - additionalPrinterColumns:
        - jsonPath: .metadata.ownerReferences[0].kind
          name: OwnerKind
          type: string
        - jsonPath: .metadata.ownerReferences[0].name
          name: Owner
          type: string
        - jsonPath: .status.conditions[?(@.type=='Succeeded')].status
          name: Succeeded
          type: string
        - jsonPath: .status.conditions[?(@.type=='Succeeded')].reason
          name: Reason
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: StartTime
          type: string
        - jsonPath: .status.conditions[?(@.type=='Succeeded')].lastTransitionTime
          name: EndTime
          type: string
      name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ include "tekton.name" . }}'
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "tekton.chart" . }}'
    pipeline.tekton.dev/release: v0.44.0
    version: v0.44.0
  name: runs.tekton.dev
spec:
  group: tekton.dev
  names:
    categories:
      - tekton
      - tekton-pipelines
    kind: Run
    plural: runs
    singular: run
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=="Succeeded")].status
          name: Succeeded
          type: string
        - jsonPath: .status.conditions[?(@.type=="Succeeded")].reason
          name: Reason
          type: string
        - jsonPath: .status.startTime
          name: StartTime
          type: date
        - jsonPath: .status.completionTime
          name: CompletionTime
          type: date
      name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ include "tekton.name" . }}'
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "tekton.chart" . }}'
    pipeline.tekton.dev/release: v0.44.0
    version: v0.44.0
  name: taskruns.tekton.dev
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: tekton-pipelines-webhook
          namespace: tekton-pipelines
      conversionReviewVersions:
        - v1beta1
        - v1
  group: tekton.dev
  names:
    categories:
      - tekton
      - tekton-pipelines
    kind: TaskRun
    plural: taskruns
    shortNames:
      - tr
      - trs
    singular: taskrun
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=="Succeeded")].status
          name: Succeeded
          type: string
        - jsonPath: .status.conditions[?(@.type=="Succeeded")].reason
          name: Reason
          type: string
        - jsonPath: .status.startTime
          name: StartTime
          type: date
        - jsonPath: .status.completionTime
          name: CompletionTime
          type: date
      name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
    - additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=="Succeeded")].status
          name: Succeeded
          type: string
        - jsonPath: .status.conditions[?(@.type=="Succeeded")].reason
          name: Reason
          type: string
        - jsonPath: .status.startTime
          name: StartTime
          type: date
        - jsonPath: .status.completionTime
          name: CompletionTime
          type: date
      name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ include "tekton.name" . }}'
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "tekton.chart" . }}'
    pipeline.tekton.dev/release: v0.44.0
    version: v0.44.0
  name: tasks.tekton.dev
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: tekton-pipelines-webhook
          namespace: tekton-pipelines
      conversionReviewVersions:
        - v1beta1
        - v1
  group: tekton.dev
  names:
    categories:
      - tekton
      - tekton-pipelines
    kind: Task
    plural: tasks
    singular: task
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
