apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: resolvers
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ include "tekton.name" . }}'
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ include "tekton.chart" . }}'
    pod-security.kubernetes.io/enforce: restricted
  name: tekton-pipelines-resolvers
