{{ if .Values.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "deduplication_db_migrations.fullname" . }}
  labels:
    {{- include "deduplication_db_migrations.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: enrichment-db-migrations
      labels:
        {{- include "deduplication_db_migrations.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: enrichment-db-migrations
        image: "{{ default "ghcr.io/ocurity/dracon" .Values.image.registry }}/draconctl:{{ default .Chart.AppVersion .Values.image.tag }}"
        env:
          - name: DRACONCTL_MIGRATIONS_PATH
            value: "/etc/dracon/migrations/enrichment"
        command:
        - draconctl
        - migrations
        - apply
        - --url
        - "postgresql://{{ .Values.database.auth.username }}:{{ .Values.database.auth.password }}@{{ .Values.database.host }}/{{ .Values.database.auth.database }}?{{ .Values.database.auth.querystringargs}}"
        - ${DRACONCTL_MIGRATIONS_PATH}
      serviceAccountName: {{ include "deduplication_db_migrations.fullname" . }}
{{ end }}
