{{ if .Values.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "deduplication_db_migrations.fullname" . }}
  labels:
    {{- include "deduplication_db_migrations.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: enrichment-db-migrations
      labels:
        {{- include "deduplication_db_migrations.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: enrichment-db-migrations
        # image.tag is set because you can't do helm upgrade and set the chart AppVersion manually
        image: "{{ default "ghcr.io/ocurity/dracon" .Values.image.registry }}/draconctl:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: DRACONCTL_MIGRATIONS_PATH
            value: "/etc/dracon/migrations/enrichment"
        command:
        - draconctl
        - migrations
        - apply
        - --url
        - "postgresql://{{ .Values.database.auth.username }}:{{ .Values.database.auth.password }}@{{ .Values.database.host }}/{{ .Values.database.auth.database }}?{{ .Values.database.auth.querystringargs}}"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: {{ include "deduplication_db_migrations.fullname" . }}
{{ end }}
