{{ if .Values.create_role }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "deduplication_db_migrations.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "deduplication_db_migrations.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "deduplication_db_migrations.fullname" . }}
{{ end }}
