---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -npm-audit-purl-project
components:
  - pkg:helm/dracon-oss-components/base
  - pkg:helm/dracon-oss-components/source-dependency
  - pkg:helm/dracon-oss-components/producer-typescript-npm-audit
  - pkg:helm/dracon-oss-components/producer-aggregator
  - pkg:helm/dracon-oss-components/enricher-deduplication
  - pkg:helm/dracon-oss-components/enricher-aggregator
  - pkg:helm/dracon-oss-components/consumer-mongodb