---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-python-bandit
  labels:
    v1.dracon.ocurity.com/component: producer
spec:
  volumes:
  - name: scratch
    emptyDir: {}
  workspaces:
    - name: source-code-ws
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-bandit
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.container_registry }}/components/producers/python-bandit/tool:latest'
    script: |
      bandit \
        --recursive \
        $(workspaces.source-code-ws.path) \
        --format json \
        --output /scratch/out.json \
        || true
    volumeMounts:
    - mountPath: /scratch
      name: scratch

  - name: produce-issues
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.container_registry }}/components/producers/python-bandit/image:latest'
    command: ["app/components/producers/python-bandit/python-bandit-parser"]
    args:
    - "-in=/scratch/out.json"
    - "-out=$(workspaces.source-code-ws.path)/.dracon/producers/python-bandit.pb"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
