---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: enricher-depsdev
  labels:
    v1.dracon.ocurity.com/component: enricher
spec:
  description: Adds context from deps.dev for each third-party dependency.
  params:
  - name: enricher-depsdev-licenses-in-evidence
    type: string
    default: "false"
  - name: enricher-depsdev-scorecard-info
    type: string
    default: "true"
  - name: enricher-depsdev-annotation
    type: string
    default: ""

  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-enricher
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.image.registry }}/components/enrichers/depsdev:{{ .Chart.AppVersion }}'
    command: ["/app/components/enrichers/depsdev/depsdev"]
    env:
    - name: READ_PATH
      value: $(workspaces.output.path)/.dracon/producers
    - name: WRITE_PATH
      value: "$(workspaces.output.path)/.dracon/enrichers/depsdev"
    - name: LICENSES_IN_EVIDENCE
      value: "$(params.enricher-depsdev-licenses-in-evidence)"
    - name: ANNOTATION
      value: "$(params.enricher-depsdev-annotation)"
    - name: SCORECARD_INFO
      value: "$(params.enricher-depsdev-scorecard-info)"
