---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-zaproxy
  labels:
    v1.dracon.ocurity.com/component: producer
spec:
  params:
  - name: producer-zaproxy-target
    type: string
    default: ""
  - name: producer-zaproxy-config-file-base64
    type: string
    default: ""
  - name: producer-zaproxy-flags
    type: string
    default: ""
  - name: producer-zaproxy-automation-framework-file-base64
    type: string
    default: ""
  volumes:
    - name: scratch
      emptyDir: {}
  workspaces:
    - name: source-code-ws
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-zap
    image: docker.io/owasp/zap2docker-stable:2.12.0
    script: |
     #! /bin/bash
      set -ex
      automation="$(params.producer-zaproxy-automation-framework-file-base64)"
      configFile="$(params.producer-zaproxy-config-file-base64)"
      if [ -z "$automation" ]; then 
        if [ -z  "$configFile" ]; then
          echo "Running ZAP with args: $(params.producer-zaproxy-flags)"
          zap.sh -cmd -silent -notel -quickout /zap/wrk/out.json -quickurl $(params.producer-zaproxy-target) $(params.producer-zaproxy-flags)
        else 
          echo "$configFile" | base64 -d > configuration.xml
          zap.sh -cmd -silent -notel -quickout /zap/wrk/out.json -quickurl $(params.producer-zaproxy-target) -configFile configuration.xml
          $(p..arams.producer-zaproxy-flags)
        fi
      else 
        echo "$automation" | base64 -d > automation.yaml
        cat automation.yaml
        zap.sh -cmd -autorun automation.yaml
      fi
    volumeMounts:
    - mountPath: /zap/wrk
      name: scratch

  - name: produce-issues
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.container_registry }}/components/producers/zaproxy/image:{{ default "latest" .Values.dracon_os_component_version }}'
    command: ["/app/components/producers/zaproxy/zaproxy-parser"]
    args:
    - "-in=/scratch/out.json"
    - "-out=$(workspaces.source-code-ws.path)/.dracon/producers/zap.pb"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
