---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-owasp-zaproxy
  labels:
    v1.dracon.ocurity.com/component: producer
spec:
  params:
  - name: producer-owasp-zaproxy-flags
    type: array
    default: []
  - name: producer-owasp-zaproxy-automation-framework-file-base64
    type: string
    default: ""
  volumes:
    - name: scratch
      emptyDir: {}
  workspaces:
    - name: source-code-ws
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-zap
    image: docker.io/owasp/zap2docker-stable:2.12.0
    script: |
     #! /bin/bash
      set -ex
      echo "$(params.producer-owasp-zaproxy-automation-framework-file-base64)" | base64 -d > automation.yaml
      cat automation.yaml
      zap.sh -cmd -autorun automation.yaml
    volumeMounts:
    - mountPath: /zap/wrk
      name: scratch

  - name: produce-issues
    imagePullPolicy: IfNotPresent
    image: ghcr.io/ocurity/dracon/components/producers/zaproxy/image:latest
    command: ["app/components/producers/zaproxy/zaproxy-parser"]
    args:
    - "-in=/scratch/out.json"
    - "-out=$(workspaces.source-code-ws.path)/.dracon/producers/zap.pb"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
