
elasticsearch:
  enabled: true
  version: 8.3.2

kibana:
  enabled: true
  version: 8.3.2
  ingress:
    enabled: true
    className: nginx
    host: kibana.dracon.localhost
    tlsEnabled: false

mongodb:
  enabled: false
  auth:
    enabled: true
    usernames: ["consumer-mongodb"]
    passwords: ["consumer-mongodb"]
    databases: ["consumer-mongodb"]

arangodb:
  enabled: false
  version: 3.7.10
  ingress:
    className: nginx
    host: arangodb.dracon.localhost

image:
  registry: kind-registry:5000/ocurity/dracon

database: &psqlConfig
  host: dracon-postgresql:5432
  auth:
    username: dracon
    password: dracon
    database: dracon
    postgresPassword: dracon
    querystringargs: "sslmode=disable"

postgresql:
  enabled: true
  <<: *psqlConfig

tekton:
  enabled: true

deduplication-db-migrations:
  enabled: true
  database: *psqlConfig
