---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dracon-checkov-project-
  namespace: dracon
spec:
  pipelineRef:
    name: dracon-checkov-project
  params:
  - name: git-clone-url
    value:  https://github.com/bridgecrewio/cfngoat
  - name: producer-checkov-cyclonedx-target-override
    value: "pkg:terraform/bridgecrewio/cfngoat"
  workspaces:
  - name: output
    subPath: source-code
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
