---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -e2e-project
namespace: dracon

resources:
  - ../../../components/base

components:
  - ../../../components/sources/git
  
  - ../../../components/producers/aggregator
  - ../../../components/producers/docker-trivy
  
  - ../../../components/producers/golang-gosec
  - ../../../components/producers/golang-nancy
  
  - ../../../components/producers/kics
  
  - ../../../components/producers/python-bandit
  - ../../../components/producers/python-pip-safety

  - ../../../components/producers/ossf-scorecard

  - ../../../components/producers/semgrep

  - ../../../components/producers/terraform-tfsec

  - ../../../components/producers/testsslsh

  - ../../../components/producers/typescript-npm-audit
  - ../../../components/producers/typescript-eslint

  - ../../../components/producers/zaproxy

  - ../../../components/enrichers/aggregator
  - ../../../components/enrichers/policy
  - ../../../components/enrichers/deduplication
  - ../../../components/consumers/mongodb
  - ../../../components/consumers/elasticsearch
