---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-dependency-check
  labels:
    v1.dracon.ocurity.com/component: producer
spec:
  volumes:
    - name: scratch
      emptyDir: {}
  workspaces:
    - name: source-code-ws
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-dependency-check
    image: docker.io/owasp/dependency-check:7.4.4
    command: [/usr/share/dependency-check/bin/dependency-check.sh]
    args:
    - -f
    - JSON
    - -o
    - /scratch
    - -s
    - $(workspaces.source-code-ws.path)/
    volumeMounts:
    - mountPath: /scratch
      name: scratch
  - name: produce-issues
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.container_registry }}/components/producers/dependency-check/image:latest'
    command: ["app/components/producers/dependency-check/dependency-check-parser"]
    args:
    - "-in=/scratch/dependency-check-report.json"
    - "-out=$(workspaces.source-code-ws.path)/.dracon/producers/dependency-check.pb"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
