---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-typescript-npm-audit
  labels:
    v1.dracon.ocurity.com/component: producer
    v1.dracon.ocurity.com/test-type: sca
spec:
  params:
    - name: producer-typescript-npm-audit-input-dependency-file
      type: string
      default: ""
  volumes:
    - name: scratch
      emptyDir: {}
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
    - name: run-npm-audit
      imagePullPolicy: IfNotPresent
      image: docker.io/node:lts
      script: |
        #!/usr/bin/env bash
        set -x
        cd $(workspaces.output.path)
        npm i --package-lock-only
        npm audit --json > /scratch/out.json || true
      volumeMounts:
        - mountPath: /scratch
          name: scratch

    - name: produce-issues
      imagePullPolicy: IfNotPresent
      image: '{{ default "ghcr.io/ocurity/dracon" .Values.container_registry }}/components/producers/typescript-npm-audit:latest'
      command:
        ["/app/components/producers/typescript-npm-audit/npm-audit-parser"]
      args:
        - "-in=/scratch/out.json"
        - "-out=$(workspaces.output.path)/.dracon/producers/typescript-npm-audit.pb"
      volumeMounts:
        - mountPath: /scratch
          name: scratch
