---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -reachability-pipeline
components:
  - pkg:helm/dracon-oss-components/base
  - pkg:helm/dracon-oss-components/git-clone
  - pkg:helm/dracon-oss-components/producer-python-bandit
  - pkg:helm/dracon-oss-components/producer-python-pip-safety
#  - local reachability
