---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -java-project
namespace: dracon

resources:
  - ../../../components/base

components:
  - ../../../components/sources/git
  
  - ../../../components/producers/aggregator
  
  - ../../../components/producers/dependency-check
  - ../../../components/producers/java-findsecbugs
  - ../../../components/enrichers/aggregator
  - ../../../components/enrichers/policy
  - ../../../components/enrichers/deduplication
  - ../../../components/consumers/mongodb
