---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dracon-snyk-node-project-
spec:
  pipelineRef:
    name: dracon-snyk-node-project
  params:
  - name: git-clone-url
    value: https://github.com/appsecco/dvna.git
  - name: producer-snyk-node-api-key
    value: "$snyk-api-key"
  workspaces:
  - name: output
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
