---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-example-tool
  labels:
    v1.dracon.ocurity.com/component: producer
spec:
  params:
  - name: producer-golang-example-tool
    type: array
    default:
    - "-r"
    - "-quiet"
    - "-sort"
    - "-nosec"
  volumes:
    - name: scratch
      emptyDir: {}
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-example-tool
    image: docker.io/example/tool:2.15.0
    command: [toolcommand]
    args:
    - "$(params.producer-example-tool-flags[*])"
    - "-fmt=json"
    - "-out=/scratch/out.json"
    - "-no-fail"
    - "$(workspaces.output.path)/..."
    volumeMounts:
    - mountPath: /scratch
      name: scratch

  - name: produce-issues
    imagePullPolicy: IfNotPresent
    image: ghcr.io/ocurity/dracon/components/producers/example-tool/image:latest
    command: ["/app/components/producers/example-tool/example-tool-parser"]
    args:
    - "-in=/scratch/out.json"
    - "-out=$(workspaces.output.path)/.dracon/producers/example-tool.pb"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
