---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-typescript-yarn-audit
  labels:
    v1.dracon.ocurity.com/component: producer
    v1.dracon.ocurity.com/test-type: sca
spec:
  volumes:
    - name: scratch
      emptyDir: {}
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
    - name: run-yarn-audit
      imagePullPolicy: IfNotPresent
      image: docker.io/node:lts
      script: |
        cd $(workspaces.output.path)
        echo "Starting yarn audit command..."
        yarn audit --json --silent --no-progress > /scratch/out.json || true
        echo "Done"
      volumeMounts:
        - mountPath: /scratch
          name: scratch

    - name: produce-issues
      imagePullPolicy: IfNotPresent
      image: '{{ default "ghcr.io/ocurity/dracon" .Values.container_registry }}/components/producers/typescript-yarn-audit:latest'
      command:
        ["/app/components/producers/typescript-yarn-audit/typescript-yarn-audit-parser"]
      args:
        - "-in=/scratch/out.json"
        - "-out=$(workspaces.output.path)/.dracon/producers/typescript-yarn-audit.pb"
      volumeMounts:
        - mountPath: /scratch
          name: scratch
