---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-typescript-yarn-audit
  labels:
    v1.dracon.ocurity.com/component: producer
spec:
  volumes:
  - name: scratch
    emptyDir: {}
  workspaces:
    - name: source-code-ws
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-yarn-audit
    imagePullPolicy: IfNotPresent
    image: docker.io/node:lts
    script: |
      cd $(workspaces.source-code-ws.path)
      yarn audit --json --silent --no-progress > /scratch/out.json || true
    volumeMounts:
    - mountPath: /scratch
      name: scratch

  - name: produce-issues
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.container_registry }}/components/producers/typescript-eslint/image:latest'
    command: ["app/components/producers/typescript-yarn-audit/yarn-audit-parser"]
    args:
    - "-in=/scratch/out.json"
    - "-out=$(workspaces.source-code-ws.path)/.dracon/producers/typescript-eslint.pb"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
