---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -defectdojo-project

resources:
  - ../../../components/base/pipeline.yaml
  - ../../../components/base/task.yaml
components:
  - ../../../components/sources/git/task.yaml
  - ../../../components/producers/aggregator/task.yaml
  - ../../../components/producers/trufflehog/task.yaml
  - ../../../components/enrichers/aggregator/task.yaml
  - ../../../components/enrichers/policy/task.yaml
  - ../../../components/consumers/mongodb/task.yaml
  - ../../../components/consumers/defectdojo/task.yaml
