---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -reachability-project
components:
  - pkg:helm/dracon-oss-components/base
  - pkg:helm/dracon-oss-components/git-clone
  - pkg:helm/dracon-oss-components/producer-python-bandit
  - pkg:helm/dracon-oss-components/producer-python-pip-safety
  - pkg:helm/dracon-oss-components/producer-aggregator
  - pkg:helm/dracon-oss-components/enrichers/reachability
  - pkg:helm/dracon-oss-components/enricher-codeowners
  - pkg:helm/dracon-oss-components/enricher-aggregator
