---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: reachability-project-
  namespace: dracon
spec:
  pipelineRef:
    name: dracon-reachability-project
  params:
  - name: git-clone-url
    value: https://github.com/fportantier/vulpy.git
  - name: enricher-reachability-programming-language
    value: python
  workspaces:
  - name: output
    subPath: source-code
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
