---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -github-project
namespace: dracon

resources:
  - ../../../components/base/pipeline.yaml
  - ../../../components/base/task.yaml
components:
  - ../../../components/sources/git/task.yaml
  - ../../../components/producers/aggregator/task.yaml
  - ../../../components/producers/golang-gosec/task.yaml
  - ../../../components/producers/golang-nancy/task.yaml
  - ../../../components/enrichers/aggregator/task.yaml
  # - ../../../components/enrichers/deduplication/task.yaml
  - ../../../components/enrichers/policy/task.yaml
  - ../../../components/consumers/mongodb/task.yaml
  - ../../../components/consumers/github/task.yaml
