---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dracon-snyk-project-
spec:
  pipelineRef:
    name: dracon-snyk-project
  params:
  - name: git-clone-url
    value: https://github.com/adeyosemanputra/pygoat.git
  - name: producer-snyk-docker-api-key
    value: "$snyk-api-key"
  - name: producer-snyk-docker-image
    value: ubuntu

  - name: producer-snyk-python-api-key
    value: "$snyk-api-key"
  - name: producer-snyk-python-relative-path-to-requirements-txt
    value: "./requirements.txt"

  workspaces:
  - name: output
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
