---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dracon-annotation-project-
spec:
  pipelineRef:
    name: dracon-annotation-project
  params:
  - name: git-clone-url
    value: https://github.com/sqreen/go-dvwa.git
  - name: enricher-custom-annotation-base-annotation
    value: |
      {"foo":"bar",
      "a":"b",
      "1":"2"}
  - name:  enricher-custom-annotation-name
    value: "bar"
  workspaces:
  - name: output
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
