---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: consumer-stdout-json
  labels:
    v1.dracon.ocurity.com/component: consumer
spec:
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-consumer
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/ocurity/dracon" .Values.container_registry }}/components/consumers/stdout-json:latest'
    command: ["/app/components/consumers/stdout-json/stdout-json"]
    args:
      - "-in"
      - "$(workspaces.output.path)/.dracon/enrichers/"
