---
name: Lint
on:
  pull_request:
    branches:
    - main

permissions:
  # Grant the ability to checkout the repository
  contents: read

  # Allow reviewdog to comment on PRs
  pull-requests: write

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup Go 1.21.6
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.6

    - name: Lint
      env:
        REVIEWDOG_GITHUB_API_TOKEN: "${{ github.token }}"
      run: go install github.com/reviewdog/reviewdog/cmd/reviewdog@latest && make install-lint-tools lint
