---
name: Lint
on:
  pull_request_target:
    types:
    - opened
    - synchronize
    - reopened
    branches:
    - main

permissions:
  # Grant the ability to checkout the repository
  contents: read
  # Grant the ability to write comments on a pull request
  pull-requests: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup Go 1.21.6
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.6

    - name: Setup node
      uses: actions/setup-node@v4

    - name: Setup reviewdog
      run: go install github.com/reviewdog/reviewdog/cmd/reviewdog@latest

    - name: Install linters
      run: make install-lint-tools

    - name: Lint
      env:
        REVIEWDOG_GITHUB_API_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      run: make lint
