---
name: Test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  # Grant the ability to checkout the repository
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-build
      cancel-in-progress: true
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache plz
        id: cache-plz
        uses: actions/cache@v3
        with:
          path: .plz-cache
          key: ${{ runner.os }}-plz

      - name: Build
        env:
          # This uses a public read-only PAT tied to VJftw, please don't abuse! :pray:
          # See: https://github.com/actions/setup-node/issues/49 for reasons.
          GITHUB_TOKEN: ${{ secrets.VJFTW_GITHUB_TOKEN }}
          CONSUMER_JIRA_API_TOKEN: ${{secrets.CONSUMER_JIRA_API_TOKEN}}
          CONSUMER_JIRA_USER: ${{secrets.CONSUMER_JIRA_USER}}
          CONSUMER_JIRA_URL: ${{secrets.CONSUMER_JIRA_URL}}
        run: make build

  test:
    name: Test
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-test
      cancel-in-progress: true
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go 1.21.6
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.6

      - name: Test
        run: make test
